#!/bin/sh
MODKEY=Mod1

local_events() { true; }

local_events() {
        cat <<'!'
Key XF86AudioRaiseVolume
        amixer -c 0 set Master 2%+ unmute && ~/.wmii/bin/volume &
Key XF86AudioLowerVolume
        amixer -c 0 set Master 2%- unmute && ~/.wmii/bin/volume &
Key XF86AudioPlay
        echo 'p' > ~/.config/pianobar/ctl &
Key XF86AudioMute
        amixer -c 0 set Master toggle &
Key XF86Display
        dock_video
Key XF86Sleep
        /usr/sbin/pm-suspend
Key XF86ScreenSaver
        gnome-screensaver-command --lock

Key Mod4-l #lock the desktop
		gnome-screensaver-command --lock
Key Mod4-w #web browser
		google-chrome &
Key Mod4-x #shutdown
		gksudo shutdown -h now
Key Mod4-s #gxrandr
		grandr &
Key Mod4-c #mcabber
                gnome-terminal -x mcabber &
Key Mod4-i #wifi
                wicd-gtk --no-tray &
!
}

status() {
        echo -n ' Wlan0:' $(iwconfig wlan0 | sed 's/ /\n/g' | grep Quality) '|' $(acpi -b | sed 's/.*, \{0,2\}\([0-9]\{1,3\}%\),.*/Bat: \1 | /') ' Core MHz:' $(cat /proc/cpuinfo | grep 'cpu MHz' | sed 's/.*: //g; s/\..*//g;') '|' $(uptime |
        sed 's/.*://; s/,//g') '|' $(date) 
}

xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation' 8 1
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Button' 8 2
xinput set-int-prop 'TPPS/2 IBM TrackPoint' 'Evdev Wheel Emulation Axes' 8 6 7 4 5

#wmiir xwrite /ctl view "2";terminator &
#sleep 5 && wmiir xwrite /ctl view "3";gnome-terminal -x mcabber &
#sleep 2 && wmiir xwrite /ctl view "1";google-chrome &
