-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WScreen",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 742,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW<1>",
                                            ["geom"] = {
                                                ["y"] = 19,
                                                ["x"] = 1,
                                                ["w"] = 1364,
                                                ["h"] = 722,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 25165893,
                                                    ["checkcode"] = 1,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 0,
                                                        ["x"] = 0,
                                                        ["w"] = 1364,
                                                        ["h"] = 722,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 26,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 753,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<2>",
                                    ["managed"] = {
                                        [1] = {
                                            ["type"] = "WGroupCW",
                                            ["name"] = "WGroupCW",
                                            ["geom"] = {
                                                ["y"] = 19,
                                                ["x"] = 1,
                                                ["w"] = 1364,
                                                ["h"] = 733,
                                            },
                                            ["switchto"] = true,
                                            ["sizepolicy"] = "full",
                                            ["managed"] = {
                                                [1] = {
                                                    ["type"] = "WClientWin",
                                                    ["bottom"] = true,
                                                    ["windowid"] = 2097155,
                                                    ["checkcode"] = 2,
                                                    ["sizepolicy"] = "full",
                                                    ["geom"] = {
                                                        ["y"] = 5,
                                                        ["x"] = 0,
                                                        ["w"] = 1364,
                                                        ["h"] = 722,
                                                    },
                                                    ["level"] = 1,
                                                },
                                            },
                                            ["level"] = 0,
                                        },
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<2>",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 742,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "Notion WFrame<3>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 26,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 144,
                            ["x"] = 363,
                            ["w"] = 640,
                            ["h"] = 480,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["hidden"] = true,
            },
        },
    },
}

