-- This file has been generated by /usr/local/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "run:google-chrome",
    [3] = "run:gnome-sound-applet",
    [4] = "run::mcabber",
    [5] = "menu.mainmenu:session/restart",
    [6] = "run::macabber",
    [7] = "run:mcabber",
    [8] = "run:goo",
    [9] = "run:killall trayion",
    [10] = "menu.mainmenu:killall trayion",
    [11] = "run::killall trayion",
    [12] = "run:trayion",
    [13] = "workspacelayout:",
    [14] = "workspacename:",
    [15] = "run:xterm",
    [16] = "run:terminator",
    [17] = "yesno:y",
    [18] = "menu.mainmenu:styles/look_clean",
    [19] = "run:quit",
    [20] = "man:",
}

